// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WiMG7IkhElobNgwFYtSelRvs5LCQuTQ',
    appId: '1:458810270636:android:90b3f67d406a251dbf5009',
    messagingSenderId: '458810270636',
    projectId: 'todoapp-f63eb',
    storageBucket: 'todoapp-f63eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9yXWVl5bmGVMvKwLRtx2Rtn19S3ycdW8',
    appId: '1:458810270636:ios:6b768ce26e3715b4bf5009',
    messagingSenderId: '458810270636',
    projectId: 'todoapp-f63eb',
    storageBucket: 'todoapp-f63eb.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9yXWVl5bmGVMvKwLRtx2Rtn19S3ycdW8',
    appId: '1:458810270636:ios:6b768ce26e3715b4bf5009',
    messagingSenderId: '458810270636',
    projectId: 'todoapp-f63eb',
    storageBucket: 'todoapp-f63eb.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0i8lmbgUlw1jI7lL1XO24nxkQRvi-OTY',
    appId: '1:458810270636:web:b5fe30ea660e2d58bf5009',
    messagingSenderId: '458810270636',
    projectId: 'todoapp-f63eb',
    authDomain: 'todoapp-f63eb.firebaseapp.com',
    storageBucket: 'todoapp-f63eb.firebasestorage.app',
  );

}